/**
 * The system brief: a short, always-current picture of the whole system for agents that can't read
 * the docs (OpenClaw runs under launchd, which macOS keeps out of ~/Documents). Written into the
 * companion's and main agent's AGENTS.md between markers, so every session (Slack, WhatsApp; local or
 * cloud model) starts knowing the system. Refreshed daily by the morning report and by the system-events
 * collector whenever something starts failing or recovers.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { overview, type ContextIndex } from './index'
import { readIdeaStates, type IdeaState } from './ideas'

export const BRIEF_START = '<!-- system-brief:start (generated by RepoHQ factory/context/brief.ts — do not edit by hand) -->'
export const BRIEF_END = '<!-- system-brief:end -->'

export interface BriefInput {
  index: ContextIndex | null
  ideas: IdeaState[]
  failingNow: Array<{ fingerprint: string; message: string }>
  now: Date
}

export function systemBrief(b: BriefInput): string {
  const stage = (s: string) => b.ideas.filter(i => i.stage === s)
  const ideaLine = (i: IdeaState) => `${i.title.split(' — ')[0]} (${i.stage}${i.review ? `, review ${i.review.verdict} ${i.review.score}/10` : ''}${i.signals ? `, ${i.signals.uniqueVisitors} visitors / ${i.signals.signups} signups` : ''}${i.page ? `, page ${i.page.url}` : ''})`
  return [
    BRIEF_START,
    `## David's system (brief, ${b.now.toISOString().slice(0, 16).replace('T', ' ')} UTC)`,
    '',
    '**Goal:** products people use and pay for, with near-zero overhead for David and no financial risk ($0: free tiers only until something earns).',
    '',
    '**Parts:**',
    '- **RepoHQ:** dashboard of his repos (health, lifecycle, revenue): https://repohq.vercel.app.',
    '- **Factory:** fixes his repos overnight on free models and opens draft PRs; he merges.',
    '- **Idea pipeline:** research → gstack review → $0 landing-page demand test → M1 build with Claude → revenue tracked. Decisions are made on the Notion Idea Board.',
    '- **Local AI stack:** Ollama, LiteLLM, Headroom.',
    '- **OpenClaw:** you, reachable on WhatsApp and Slack #team-agents.',
    '- **Resource Center:** his bookmarks.',
    '- **System log:** watches everything and posts failures to Slack #team-agents.',
    '',
    '**Rules:**',
    '- Never touch financial data. Never pull his employer\'s work data into cloud models.',
    '- Draft PRs only, he merges.',
    '- His Notion status wins.',
    '- Claude runs on his subscription, never API credit.',
    '',
    b.index ? `**Now:** ${overview(b.index).split('\n').slice(1, 3).join(' ')}` : '',
    b.failingNow.length ? `**Failing right now (${b.failingNow.length}):** ${b.failingNow.slice(0, 6).map(f => `${f.fingerprint} — ${f.message.slice(0, 120)}`).join('; ')}` : '**Failing right now:** nothing.',
    b.ideas.length ? `**Ideas:** ${[...stage('validate'), ...stage('building'), ...stage('repo'), ...stage('live')].map(ideaLine).join('; ') || 'none in progress'}. Passed: ${stage('pass').length}.` : '',
    '',
    '**Look things up, don\'t guess:**',
    '- `/Users/davidsmith/idea-factory/bin/context search "<words>"` (repos, ideas, interests, docs) or `overview`;',
    '- `/Users/davidsmith/ai-stack/bin/system-status` (what\'s failing, the last 24 h per system);',
    '- an idea\'s full record: `/Users/davidsmith/idea-factory/ideas/<slug>/`.',
    '',
    'The full map is RepoHQ `docs/system-overview.md`.',
    BRIEF_END,
  ].filter(l => l !== null).join('\n')
}

/** Replace (or append) the brief block in a markdown file. Pure. */
export function withBrief(markdown: string, brief: string): string {
  const s = markdown.indexOf(BRIEF_START)
  const e = markdown.indexOf(BRIEF_END)
  if (s >= 0 && e > s) return markdown.slice(0, s) + brief + markdown.slice(e + BRIEF_END.length)
  return `${markdown.replace(/\s*$/, '')}\n\n${brief}\n`
}

export const OPENCLAW_AGENTS_FILES = ['workspace-companion/AGENTS.md', 'workspace/AGENTS.md']

/** Write the brief into each OpenClaw agent's AGENTS.md. Returns the files written. */
export function writeOpenClawBrief(brief: string, home = process.env.HOME ?? ''): string[] {
  const written: string[] = []
  for (const rel of OPENCLAW_AGENTS_FILES) {
    const f = path.join(home, '.openclaw', rel)
    if (!existsSync(f)) continue
    const before = readFileSync(f, 'utf8')
    const after = withBrief(before, brief)
    if (after !== before) { writeFileSync(f, after); written.push(f) }
  }
  return written
}

/** Load the index and idea records from their homes and rewrite the OpenClaw brief. Never throws. */
export function refreshOpenClawBrief(failingNow: BriefInput['failingNow'], now = new Date()): string[] {
  try {
    const home = process.env.HOME ?? ''
    const indexFile = path.join(home, '.repohq-factory', 'context', 'index.json')
    const index = existsSync(indexFile) ? JSON.parse(readFileSync(indexFile, 'utf8')) as ContextIndex : null
    const ideas = readIdeaStates(process.env.IDEA_HOME ?? path.join(home, 'idea-factory'))
    return writeOpenClawBrief(systemBrief({ index, ideas, failingNow, now }), home)
  } catch {
    return []
  }
}
