-- Roadmap Phase 79: autonomous factory job record (src/lib/db/schema.ts `agentJobs`).
-- Generated by drizzle-kit from the schema, made idempotent. Apply: npm run factory:migrate
CREATE TABLE IF NOT EXISTS "agent_jobs" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"repo_id" integer,
	"repo" text NOT NULL,
	"parent_job_id" text,
	"run_id" text NOT NULL,
	"task_kind" text NOT NULL,
	"pipeline" text,
	"tier" text NOT NULL,
	"model" text NOT NULL,
	"harness" text NOT NULL,
	"isolation" text,
	"status" text NOT NULL,
	"reason" text,
	"requests" integer,
	"input_tokens" integer DEFAULT 0,
	"output_tokens" integer DEFAULT 0,
	"cost_usd" real DEFAULT 0,
	"duration_ms" integer,
	"reported" boolean DEFAULT false,
	"pr_url" text,
	"adversary_model" text,
	"adversary_verdict" text,
	"outcome" text,
	"human_commits" integer,
	"started_at" timestamp NOT NULL,
	"resolved_at" timestamp
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'agent_jobs_user_id_users_id_fk') THEN
    ALTER TABLE "agent_jobs" ADD CONSTRAINT "agent_jobs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'agent_jobs_repo_id_repositories_id_fk') THEN
    ALTER TABLE "agent_jobs" ADD CONSTRAINT "agent_jobs_repo_id_repositories_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repositories"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS "agent_jobs_user_started_idx" ON "agent_jobs" USING btree ("user_id","started_at");
