-- Roadmap Phase 81: Agent HQ queue (docs/agent-hq-migration-prd.md §5) — agent_requests,
-- automation_runs, trace_events and agent_jobs.request_id (src/lib/db/schema.ts).
-- Generated by drizzle-kit from the schema, made idempotent. Apply: npm run factory:migrate
CREATE TABLE IF NOT EXISTS "agent_requests" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"repo_id" integer,
	"repo" text NOT NULL,
	"mode" text NOT NULL,
	"skill" text,
	"objective" text NOT NULL,
	"source" text NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"pr_url" text,
	"findings" text,
	"reason" text,
	"run_id" text,
	"attempts" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"claimed_at" timestamp,
	"resolved_at" timestamp,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS "automation_runs" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text,
	"kind" text NOT NULL,
	"trigger" text NOT NULL,
	"request_id" text,
	"job_id" text,
	"status" text NOT NULL,
	"summary" jsonb,
	"error" text,
	"started_at" timestamp DEFAULT now() NOT NULL,
	"finished_at" timestamp
);
CREATE TABLE IF NOT EXISTS "trace_events" (
	"id" serial PRIMARY KEY NOT NULL,
	"run_id" text NOT NULL,
	"request_id" text,
	"job_id" text,
	"at" timestamp DEFAULT now() NOT NULL,
	"step" text NOT NULL,
	"status" text NOT NULL,
	"detail" text,
	"data" jsonb,
	"duration_ms" integer
);
ALTER TABLE "agent_jobs" ADD COLUMN IF NOT EXISTS "request_id" text;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'agent_requests_user_id_users_id_fk') THEN
    ALTER TABLE "agent_requests" ADD CONSTRAINT "agent_requests_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'agent_requests_repo_id_repositories_id_fk') THEN
    ALTER TABLE "agent_requests" ADD CONSTRAINT "agent_requests_repo_id_repositories_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repositories"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'automation_runs_user_id_users_id_fk') THEN
    ALTER TABLE "automation_runs" ADD CONSTRAINT "automation_runs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'trace_events_run_id_automation_runs_id_fk') THEN
    ALTER TABLE "trace_events" ADD CONSTRAINT "trace_events_run_id_automation_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."automation_runs"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS "agent_jobs_request_idx" ON "agent_jobs" USING btree ("request_id");
CREATE INDEX IF NOT EXISTS "agent_requests_user_status_idx" ON "agent_requests" USING btree ("user_id","status");
CREATE INDEX IF NOT EXISTS "agent_requests_repo_created_idx" ON "agent_requests" USING btree ("repo_id","created_at");
CREATE INDEX IF NOT EXISTS "automation_runs_started_idx" ON "automation_runs" USING btree ("started_at");
CREATE INDEX IF NOT EXISTS "automation_runs_kind_started_idx" ON "automation_runs" USING btree ("kind","started_at");
CREATE INDEX IF NOT EXISTS "trace_events_run_at_idx" ON "trace_events" USING btree ("run_id","at");
CREATE INDEX IF NOT EXISTS "trace_events_request_idx" ON "trace_events" USING btree ("request_id");
