import type { ModelTier } from '../../src/lib/agents/model-router'
import type { CheckResult } from './checks'
import type { FactoryTask } from './tasks'
import type { DiffInfo } from './verify'

/** Roadmap Phase 70 standard for autonomous work: feature/bot/{taskId}-{slug}. */
export function branchName(task: FactoryTask, now: Date, runId: string): string {
  return `feature/bot/factory-${now.toISOString().slice(0, 10).replace(/-/g, '')}-${runId.slice(-4)}-${task.kind}`
}

export function commitMessage(task: FactoryTask, tier: ModelTier, model: string): string {
  return `${task.kind === 'docs-readme' ? 'docs' : 'fix'}: ${task.title.toLowerCase()}\n\nGenerated by RepoHQ Factory (${tier} · ${model}). Verified by the repo's own checks before opening this draft PR.`
}

export function prTitle(task: FactoryTask): string {
  return `[factory] ${task.title}`
}

const mark = (r: CheckResult | undefined) => (r ? (r.ok ? '✅' : '❌') : '—')

export function prBody(input: {
  task: FactoryTask
  tier: ModelTier
  model: string
  harness: string
  verdict: string
  baseline: CheckResult[]
  after: CheckResult[]
  diff: DiffInfo
  durationMs: number
  costUsd: number
  exploring: boolean
}): string {
  const { task, baseline, after } = input
  const names = [...new Set([...baseline, ...after].map(r => r.name))]
  const rows = names.map(n => `| ${n} | ${mark(baseline.find(b => b.name === n))} | ${mark(after.find(a => a.name === n))} |`)
  return [
    '## What',
    task.objective,
    '',
    '<details><summary>Evidence</summary>',
    '',
    '```',
    task.evidence.slice(0, 3000),
    '```',
    '</details>',
    '',
    '## Verification',
    '| Check | Before | After |',
    '|---|---|---|',
    ...rows,
    '',
    `Judge: ${input.verdict}`,
    '',
    '## Changes',
    ...input.diff.files.map(f => `- \`${f.path}\` +${f.added}/-${f.removed}`),
    '',
    '## Provenance',
    `- Tier **${input.tier}**${input.exploring ? ' (exploration run)' : ''} · ${input.harness} · \`${input.model}\``,
    `- ${Math.round(input.durationMs / 1000)}s · $${input.costUsd.toFixed(2)}`,
    '',
    '_Draft opened by the RepoHQ autonomous factory (docs/autonomous-factory.md). Merging is always a human decision; merge or close to teach the router._',
  ].join('\n')
}
